# Generated by Django 5.1 on 2025-11-21 04:56

import client.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(20)], verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)], verbose_name='Address')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='client_documents/', verbose_name='Agreement Document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, help_text='Optional. PDF or DOCX only. Max 5 MB.', null=True, upload_to='contact_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), client.models.validate_file_size])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to='client.clientprofile', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(100)], verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(1000)], verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='client.clientprofile', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance Amount')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_payments', to='client.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, help_text='Optional. PDF or DOCX only. Max 5 MB.', null=True, upload_to='contact_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), client.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='client.project', verbose_name='Project')),
            ],
        ),
    ]
