# Generated by Django 5.1 on 2025-11-21 05:10

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='agreement_document',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
            preserve_default=False,
        ),
    ]
