# Generated by Django 5.1 on 2025-11-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clientprofile_agreement_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brief',
            field=models.FileField(blank=True, help_text='Upload PDF/DOCX (Optional)', null=True, upload_to='project_briefs/', verbose_name='Project Brief Document'),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverables',
            field=models.TextField(blank=True, help_text='Add each deliverable on a new line.', null=True, verbose_name='Key Deliverables'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0, help_text='0\xa0to\xa0100', verbose_name='Project Progress (%)'),
        ),
    ]
