# Generated by Django 5.1 on 2025-11-24 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_project_brief_project_deliverables_project_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('mode', models.CharField(choices=[('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, verbose_name='Payment Mode')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction / UTR / Cheque No.')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note (optional)')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Status')),
                ('admin_reason', models.TextField(blank=True, null=True, verbose_name='Admin Reason (if Rejected)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='client.clientprofile', verbose_name='Client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='client.project', verbose_name='Project')),
            ],
        ),
    ]
