# Generated by Django 5.1 on 2025-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='added_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
