# Generated by Django 5.1 on 2025-11-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_clientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='uploaded_by',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='attachment',
            field=models.FileField(upload_to='project_docs/'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.project'),
        ),
    ]
