# Generated by Django 5.1 on 2025-11-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_projectdocument_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_docs/'),
        ),
    ]
