# Generated by Django 5.1 on 2025-11-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_projectdocument_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/', verbose_name='Payment Proof Screenshot'),
        ),
    ]
