# Generated by Django 5.1 on 2025-12-01 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50)], verbose_name='Full Name'),
        ),
    ]
