# Generated by Django 5.1 on 2025-12-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_clientprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/', verbose_name='Payment Screenshot'),
        ),
    ]
