# Generated by Django 5.1 on 2025-12-02 05:29

import client.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_paymentrequest_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldocument',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'jpeg', 'png']), client.models.validate_file_size]),
        ),
    ]
