# Generated by Django 5.1 on 2025-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_personaldocument_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='payment_status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Not Assigned', max_length=20),
        ),
    ]
