# Generated by Django 5.2.6 on 2025-11-06 15:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import website.fields
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('story', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Value',
                'verbose_name_plural': 'Company Values',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(15)])),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('message', website.fields.EncryptedTextField(help_text='Max 500 characters (stored encrypted).', validators=[django.core.validators.MaxLengthValidator(500)])),
                ('attachment', models.FileField(blank=True, help_text='Optional. PDF or DOCX only. Max 5 MB.', null=True, upload_to='contact_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), website.models.validate_file_size])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', website.fields.EncryptedTextField(blank=True, null=True)),
                ('email', website.fields.EncryptedTextField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('order', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('full_description', models.TextField(blank=True, max_length=250, null=True)),
                ('icon', models.CharField(blank=True, max_length=1, null=True)),
                ('color', models.CharField(choices=[('accent-green', 'Accent Green'), ('highlight-gold', 'Highlight Gold'), ('card-bg', 'Card Background')], default='accent-green', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('summary', models.TextField(help_text='A short summary for the blog listing page.')),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_legal', models.CharField(max_length=100, verbose_name='First Name (Legal)')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_number', website.fields.EncryptedTextField(verbose_name='Phone Number')),
                ('address_line1', website.fields.EncryptedTextField(verbose_name='Address Line 1')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('school', models.CharField(blank=True, max_length=150, null=True, verbose_name='School / Institution')),
                ('otp_code', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Candidate',
                'verbose_name_plural': 'Manage Candidates',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', website.fields.EncryptedTextField(blank=True, max_length=20)),
                ('resume', models.FileField(help_text='Upload your resume (PDF, DOC, DOCX, max 5 MB)', upload_to='resumes/')),
                ('cover_letter', website.fields.EncryptedTextField(blank=True, help_text='Optional short cover letter or motivation statement')),
                ('attachment', models.FileField(blank=True, help_text='Optional supporting document (PDF, DOC, DOCX, max 5 MB)', null=True, upload_to='attachments/')),
                ('graduation_year', models.IntegerField(default=2024)),
                ('graduation_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('experience', models.CharField(blank=True, default='', max_length=255)),
                ('key_skills', website.fields.EncryptedTextField(default='')),
                ('preferred_domain', models.CharField(choices=[('data_analytics', 'Data Analytics'), ('ai_ml', 'AI / ML'), ('web_dev', 'Web Development'), ('automation', 'Business Process Automation'), ('finance', 'Finance & Reporting'), ('other', 'Other')], default='other', max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='received', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.job')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', website.fields.EncryptedTextField(blank=True, max_length=15, null=True)),
                ('message', website.fields.EncryptedTextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('assigned_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.expert')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_queries', to='website.service')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('scheduled_date_date', models.DateField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('assigned_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.expert')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email', 'phone', 'scheduled_date_date'), name='unique_demo_per_day_email_phone')],
            },
        ),
    ]
