# Generated by Django 5.1 on 2025-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(choices=[('accent-green', 'Accent Green'), ('highlight-gold', 'Highlight Gold'), ('card-bg', 'Card Background')], default='accent-green', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
