# Generated by Django 5.1 on 2025-10-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertquery',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_assignments', to='website.expert'),
        ),
        migrations.AddField(
            model_name='expertquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduledemo',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_assignments', to='website.expert'),
        ),
        migrations.AddField(
            model_name='scheduledemo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
