# Generated by Django 5.1 on 2025-10-27 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_expertquery_assigned_expert_expertquery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertquery',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.expert'),
        ),
        migrations.AlterField(
            model_name='expertquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledemo',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.expert'),
        ),
        migrations.AlterField(
            model_name='scheduledemo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
