# Generated by Django 5.1 on 2025-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_expertquery_assigned_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(blank=True, help_text='Work experience details (e.g., 1 year in Data Analytics)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='graduation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Graduation percentage or CGPA', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Year of graduation (e.g., 2023)', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='key_skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills (e.g., Python, SQL, Excel)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='preferred_domain',
            field=models.CharField(blank=True, choices=[('data_analytics', 'Data Analytics'), ('ai_ml', 'AI / Machine Learning'), ('web_dev', 'Web Development'), ('automation', 'Business Process Automation'), ('finance', 'Finance & Reporting'), ('other', 'Other')], help_text='Preferred job domain', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='received', max_length=20),
        ),
    ]
