# Generated by Django 5.1 on 2025-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_jobapplication_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='graduation_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='graduation_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='key_skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='preferred_domain',
            field=models.CharField(choices=[('data_analytics', 'Data Analytics'), ('ai_ml', 'AI / ML'), ('web_dev', 'Web Development'), ('automation', 'Business Process Automation'), ('finance', 'Finance & Reporting'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='received', max_length=20),
        ),
    ]
