# Generated by Django 5.1 on 2025-10-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_candidateprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['-date_created'], 'verbose_name': 'Manage Candidate', 'verbose_name_plural': 'Manage Candidates'},
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='address_line1',
            field=models.CharField(max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='first_name_legal',
            field=models.CharField(max_length=100, verbose_name='First Name (Legal)'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='school',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='School / Institution'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(max_length=100, verbose_name='State'),
        ),
    ]
