# Generated by Django 5.1 on 2025-10-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional supporting document (PDF, DOC, DOCX, max 5 MB)', null=True, upload_to='attachments/'),
        ),
    ]
