# Generated by Django 5.2.6 on 2025-10-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_jobapplication_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
