# Generated by Django 5.1 on 2025-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_candidateprofile_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Optional short cover letter or motivation statement'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(help_text='Upload your resume (PDF, DOC, DOCX, max 5 MB)', upload_to='resumes/'),
        ),
    ]
