# Generated by Django 5.1 on 2025-10-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_aboutus_companyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
