# Generated by Django 5.2.6 on 2025-11-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
