# Generated by Django 5.1 on 2025-11-04 08:37

import website.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='address_line1',
            field=website.fields.EncryptedTextField(verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=website.fields.EncryptedTextField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=website.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='expert',
            name='email',
            field=website.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='full_name',
            field=website.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='otp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expertquery',
            name='message',
            field=website.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='expertquery',
            name='phone',
            field=website.fields.EncryptedTextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=website.fields.EncryptedTextField(blank=True, help_text='Optional short cover letter or motivation statement'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='key_skills',
            field=website.fields.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=website.fields.EncryptedTextField(blank=True, max_length=20),
        ),
    ]
