# Generated by Django 5.1 on 2025-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_candidateprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
    ]
