# Generated by Django 5.1 on 2025-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemo',
            name='scheduled_date_date',
            field=models.DateField(db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='scheduledemo',
            constraint=models.UniqueConstraint(fields=('email', 'phone', 'scheduled_date_date'), name='unique_demo_per_day_email_phone'),
        ),
    ]
