# Generated by Django 5.1 on 2025-11-07 09:15

import django.core.validators
import website.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_scheduledemo_scheduled_date_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=website.fields.EncryptedTextField(help_text='Max 500 characters (stored encrypted).', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
