# Generated by Django 5.1 on 2025-11-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_candidateprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('feedback', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
