# Generated by Django 5.1 on 2025-11-13 10:47

import website.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_chatbotqa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=website.fields.EncryptedTextField(blank=True, max_length=10),
        ),
    ]
