# Generated by Django 5.1 on 2025-11-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_alter_jobapplication_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduledemo',
            name='unique_demo_per_day_email_phone',
        ),
    ]
