# Generated by Django 5.1 on 2025-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_remove_scheduledemo_unique_demo_per_day_email_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertquery',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
