# Generated by Django 5.2.6 on 2025-11-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_expertquery_decline_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
