# Generated by Django 5.2.6 on 2025-11-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_jobapplication_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='experience',
            new_name='experience_years',
        ),
    ]
