# Generated by Django 5.1 on 2025-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_rename_experience_jobapplication_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Pincode'),
        ),
    ]
