# Generated by Django 5.1 on 2025-12-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_candidateprofile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
