"""
Django settings for propulsion_site project.

Generated by 'django-admin startproject' using Django 5.1.
"""

from pathlib import Path
import os


# ------------------------------------------------------------
# BASE CONFIGURATION
# ------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

SECRET_KEY = 'django-insecure-xmlwbev-^6fwr!*ec!f2)qlf##mql-78c3270(+_@mnnozcv(c'
#DEBUG = True
#ALLOWED_HOSTS = []

DEBUG = False

SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


ALLOWED_HOSTS = [
    "propulsiontech.in",
    "www.propulsiontech.in",
    "13.127.123.170",
    "127.0.0.1",
    "localhost",
]

CSRF_TRUSTED_ORIGINS = [
    "https://propulsiontech.in",
    "https://www.propulsiontech.in",
]


# ------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'client',
    'widget_tweaks',
]

# ------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------
#MIDDLEWARE = [
 #   'django.middleware.security.SecurityMiddleware',
  #  'django.contrib.sessions.middleware.SessionMiddleware',
   # 'django.middleware.common.CommonMiddleware',
  #  'django.middleware.csrf.CsrfViewMiddleware',
   # 'django.contrib.auth.middleware.AuthenticationMiddleware',
   # 'django.contrib.messages.middleware.MessageMiddleware',
    # 🔒 Custom Encryption Middleware
   # 'propulsion_site.middleware.encrypt_response_middleware.EncryptHTMLMiddleware',
   # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
#]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
#    'propulsion_site.middleware.encrypt_response_middleware.EncryptHTMLMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'propulsion_site.urls'

# ------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "website.views.base_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'propulsion_site.wsgi.application'

# ------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ID',
        'USER': 'postgres',
        'PASSWORD': 'postgres#123',
        'HOST': '13.127.123.170',
        'PORT': '5432',
    }
}

# ------------------------------------------------------------
# PASSWORD VALIDATION
# ------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------
# STATIC & MEDIA FILES
# ------------------------------------------------------------
#STATIC_URL = 'static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # this matches Nginx alias

# Static files (CSS, JS, images)
STATIC_URL = '/static/'

# This is the source directory for your project static files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# This is where collectstatic will put all files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Use Whitenoise for hashed files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------
# EMAIL CONFIGURATION
# ------------------------------------------------------------
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'propulsiontech381@gmail.com'
EMAIL_HOST_PASSWORD = 'gwrv nrhy jxcm gbyn'

DEFAULT_FROM_EMAIL = 'Propulsion Tech <propulsiontech381@gmail.com>'
#DEFAULT_SITE_URL = 'http://127.0.0.1:8000'
DEFAULT_SITE_URL = 'https://propulsiontech.in'

# ------------------------------------------------------------
# SESSION CONFIGURATION
# ------------------------------------------------------------
SESSION_ENGINE = "django.contrib.sessions.backends.db"
#SESSION_CACHE_ALIAS = "default"

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
 #       'LOCATION': 'unique-sessions',
    }
}

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# ------------------------------------------------------------
# PAGE ENCRYPTION SETTINGS
# ------------------------------------------------------------
# Toggle encryption on/off globally
# ENABLE_PAGE_ENCRYPTION = True

# # Server-side password used to encrypt pages (from .env or hardcoded)
# # ⚠️ Keep this secret! Use the same password in the browser to decrypt pages.
# PAGE_ENCRYPT_PASSWORD = os.getenv("PAGE_ENCRYPT_PASSWORD", "/Hyt4fC51oUiJuJ9Q56NenoN426czqoVdjwS56LZd+g=")

# # PBKDF2 iterations (must match middleware + JS)
# PAGE_ENCRYPT_KDF_ITERATIONS = 200000

# # Paths to exclude from encryption
# PAGE_ENCRYPT_EXCLUDE_PREFIXES = ["/static/", "/media/", "/api/", "/admin/"]

# # ------------------------------------------------------------
# # END OF SETTINGS
# # ------------------------------------------------------------

# Auth redirects (Admin)
LOGIN_URL = '/admin-login/'
LOGIN_REDIRECT_URL = '/admin-dashboard/'
LOGOUT_REDIRECT_URL = '/admin-login/'
#LOGIN_REDIRECT_URL = 'https://propulsiontech.in/admin-dashboard/'
#LOGOUT_REDIRECT_URL = 'https://propulsiontech.in/admin-login/'
