"""
Django settings for propulsion_site project.

Generated by 'django-admin startproject' using Django 5.1.
"""

from pathlib import Path
import os


# ------------------------------------------------------------
# BASE CONFIGURATION
# ------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

SECRET_KEY = 'django-insecure-xmlwbev-^6fwr!*ec!f2)qlf##mql-78c3270(+_@mnnozcv(c'
DEBUG = True
ALLOWED_HOSTS = []

# ------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
]

# ------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 🔒 Custom Encryption Middleware
    'propulsion_site.middleware.encrypt_response_middleware.EncryptHTMLMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'propulsion_site.urls'

# ------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "website.views.base_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'propulsion_site.wsgi.application'

# ------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'yourdatabasename',
        'USER': 'postgres',
        'PASSWORD': 'yourpassword',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# ------------------------------------------------------------
# PASSWORD VALIDATION
# ------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------
# STATIC & MEDIA FILES
# ------------------------------------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------
# EMAIL CONFIGURATION
# ------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'jayesh@creativewebsolution.in'
EMAIL_HOST_PASSWORD = 'JP@$$w0rd@123'
DEFAULT_FROM_EMAIL = 'jayesh@creativewebsolution.in'
CONTACT_EMAIL = 'jayesh@creativewebsolution.in'
DEFAULT_SITE_URL = 'http://127.0.0.1:8000'

# ------------------------------------------------------------
# SESSION CONFIGURATION
# ------------------------------------------------------------
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-sessions',
    }
}

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# ------------------------------------------------------------
# PAGE ENCRYPTION SETTINGS
# ------------------------------------------------------------
# Toggle encryption on/off globally
# ENABLE_PAGE_ENCRYPTION = True

# # Server-side password used to encrypt pages (from .env or hardcoded)
# # ⚠️ Keep this secret! Use the same password in the browser to decrypt pages.
# PAGE_ENCRYPT_PASSWORD = os.getenv("PAGE_ENCRYPT_PASSWORD", "/Hyt4fC51oUiJuJ9Q56NenoN426czqoVdjwS56LZd+g=")

# # PBKDF2 iterations (must match middleware + JS)
# PAGE_ENCRYPT_KDF_ITERATIONS = 200000

# # Paths to exclude from encryption
# PAGE_ENCRYPT_EXCLUDE_PREFIXES = ["/static/", "/media/", "/api/", "/admin/"]

# # ------------------------------------------------------------
# # END OF SETTINGS
# # ------------------------------------------------------------

